name: CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456789012

      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola mundo"
     
      - name: "Mostrando variables de entorno"
        run: |
          echo "Esto es el valor de platform: ${{ env.platform }}"
          echo "Esto es el valor de region: ${{ env.region }}"
          echo "esto es el valor de account: ${{ env.account }}"

          echo "Esto es el valor de username: ${{ env.username }}"
          echo "Esto es el valor de password: ${{ env.password }}"

          echo "Project version ${{ vars.PROJECT_VERSION }}"

      - name: "Mostrando valores solo si el usuario es correcto"
        if: ${{ env.username != '' && env.password != '' }}
        run: |
         echo "Si existe usuario y contraseña"

      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{toJSON(github.event)}}"
          echo "Githbu_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

