name: CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456789012

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola mundo"
     
      - name: "Mostrando variables de entorno"
        run: |
          echo "Esto es el valor de platform: ${{ env.platform }}"
          echo "Esto es el valor de region: ${{ env.region }}"
          echo "esto es el valor de account: ${{ env.account }}"
